# Generated by Django 3.0.3 on 2020-02-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('date_paid', models.DateTimeField()),
                ('postpaid', models.CharField(max_length=30)),
                ('prepaid', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('mobile_subscribers', models.CharField(max_length=40)),
                ('fixed_subscribers', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='InternationalInternetBandwidth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('up_link', models.CharField(max_length=20)),
                ('down_link', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='VoiceTraffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=40)),
                ('call_count', models.CharField(max_length=40)),
                ('out_going', models.BooleanField(default=True)),
                ('average_minute_per_call', models.CharField(max_length=5)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
