# Generated by Django 3.0.3 on 2020-03-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ict',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='internationalinternetbandwidth',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='voicetraffic',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
