# Generated by Django 3.0.3 on 2020-03-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rura', '0002_auto_20200303_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='ict',
            name='amount',
            field=models.CharField(default=62972, max_length=20),
        ),
    ]
